# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: position_controllers/GripperActionController

#ur3e_with_gripper:  # Ez a robot neve a Gazebo-ban
#  ros__parameters:
#    use_sim_time: true

    # Gazebo hardware interface típusa
#    gazebo:
#      use_sim_time: true

    # Ez a kritikus rész - a hardware interface típusa
#    ros2_control:
#      type: system
#      hardware_plugin: gz_ros2_control/GazeboSystem

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true

arm_trajectory_controller:
  ros__parameters:
    use_sim_time: true
    joints:
      - ur3e_shoulder_pan_joint
      - ur3e_shoulder_lift_joint
      - ur3e_elbow_joint
      - ur3e_wrist_1_joint
      - ur3e_wrist_2_joint
      - ur3e_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
gripper_controller:
  ros__parameters:
    use_sim_time: true
    joint: robotiq_85_left_knuckle_joint
