controller_list:
  # Kar vezérlő
  - name: "ur3e_arm_controller"
    type: "position_controllers/JointTrajectoryController"
    joints:
      - "shoulder_pan_joint"
      - "shoulder_lift_joint"
      - "elbow_joint"
      - "wrist_1_joint"
      - "wrist_2_joint"
      - "wrist_3_joint"
    interface: "hardware_interface/PositionJointInterface"
    action_monitor_rate: 20
    constraints:
      - joint: "shoulder_pan_joint"
        goal_tolerance: 0.01
        soft_tolerance: 0.005
        stale_time: 0.5
      - joint: "shoulder_lift_joint"
        goal_tolerance: 0.01
        soft_tolerance: 0.005
        stale_time: 0.5
      - joint: "elbow_joint"
        goal_tolerance: 0.01
        soft_tolerance: 0.005
        stale_time: 0.5
      - joint: "wrist_1_joint"
        goal_tolerance: 0.01
        soft_tolerance: 0.005
        stale_time: 0.5
      - joint: "wrist_2_joint"
        goal_tolerance: 0.01
        soft_tolerance: 0.005
        stale_time: 0.5
      - joint: "wrist_3_joint"
        goal_tolerance: 0.01
        soft_tolerance: 0.005
        stale_time: 0.5
    state_publish_rate: 50

  # Gripper vezérlő
  - name: "robotiq_gripper_controller"
    type: "position_controllers/GripperController"
    joints:
      - "robotiq_2f_gripper_finger_left_joint"
      - "robotiq_2f_gripper_finger_right_joint"
    interface: "hardware_interface/PositionJointInterface"
    action_monitor_rate: 20
    constraints:
      - joint: "robotiq_2f_gripper_finger_left_joint"
        goal_tolerance: 0.01
        soft_tolerance: 0.005
        stale_time: 0.5
      - joint: "robotiq_2f_gripper_finger_right_joint"
        goal_tolerance: 0.01
        soft_tolerance: 0.005
        stale_time: 0.5
    state_publish_rate: 50
